repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: (Common) Remove trailing whitespaces
      - id: mixed-line-ending
        name: (Common) Fix mixed line ending
        args: [--fix=lf]
      - id: end-of-file-fixer
        name: (Common) Remove extra EOF newlines
      - id: check-merge-conflict
        name: (Common) Check for merge conflicts
      - id: requirements-txt-fixer
        name: (Common) Sort "requirements.txt"
      - id: fix-encoding-pragma
        name: (Python) Remove encoding pragmas
        args: [--remove]
      - id: double-quote-string-fixer
        name: (Python) Fix double-quoted strings
      - id: debug-statements
        name: (Python) Check for debugger imports
      - id: check-json
        name: (JSON) Check syntax
      - id: check-yaml
        name: (YAML) Check syntax
        exclude: |
          (?x)^(
              conda/dgsparse/meta.yaml
          )$
      - id: check-toml
        name: (TOML) Check syntax
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        name: (Markdown) Format with mdformat
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        name: (Python) Format with yapf
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Check PEP8
        additional_dependencies: [Flake8-pyproject]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.2
    hooks:
      - id: clang-format
        name: (C/C++/CUDA) Format with clang-format
        args: [-style=llvm, -i]
        types_or: [c, c++, cuda]
